### ISSUE TITLE
Websocket based SQLA Dialect (Beta Version)

### ISSUE THREAD

**Issue by raayu83** [exasol/sqlalchemy-exasol#105]
I wonder if it would be possible to add a pyexasol backend as an alternative to odbc?

**Comment by jank** [comment]
@xyzy-web, supporting multiple drivers should not be an issue. SQLAlchemy supports identification of drivers via the URL: https://docs.sqlalchemy.org/en/13/core/engines.html#database-urls.
In folder sqlalchemy_exasol you can find how support for pyodbc and turbodbc is added. Following that schema, adding pyexasol should be possible.
Would you be willing to conribute this?

**Comment by Nicoretti** [comment]
# Status Update

In order to implement an `SQLA` dialect/driver based on `pyexasol` a `dbapi` interface is required ([pep-249](https://peps.python.org/pep-0249/)).
Due to the fact that `pyexasol` just provides this interface partially, we started implementing a `dbapi` wrapper as a first step.

## What have been done so far
- [x] Implement/Setup `SQLA` independent test setup for integration and unit tests
- [x] Implement/Setup stubs for `dbapi`
- [x] Implement/Setup `pyexasol` based wrapper for connection required by `dbapi`


##  TODO's (Pending)
- [ ] Implement/Setup `pyexasol` based wrapper for cursor required by `dbapi`
- [ ] Implement/Setup a `SQLA` driver based on the `dbapi` wrappers
- [ ] Implement/Setup the newly added test setup with the CI/CD infrastructure
- [ ] Cleanup, clarify open question's and align structure and naming of the components


## Questions
* Should the fact that `pyexasol` is used be exposed to the end-user?  `"exa+pyexasol..."` vs `"exa+ws..."` or `"exa+websocket"`
* Where should we put the `dbapi` wrapper and what should it's naming/structure be?

For further details on the current status, see also [PR-278](https://github.com/exasol/sqlalchemy-exasol/pull/278).

**Comment by Nicoretti** [comment]
# Status Update

The DBAPI2 compliant web-socket driver has been implemented (see also [PR-278](https://github.com/exasol/sqlalchemy-exasol/pull/278)).
As next step the actual  `SQLA` dialect/driver implementation will be started.

## What have been done so far
- [x] Implement/Setup `SQLA` independent test setup for integration and unit tests
- [x] Implement/Setup stubs for `dbapi`
- [x] Implement/Setup `pyexasol` based wrapper for connection required by `dbapi`
- [x] Implement/Setup `pyexasol` based wrapper for cursor required by `dbapi`
- [x] Clarify open question's and align structure and naming of the components
    * We use `exa+ws...` which will be websockets with the provided "default" implementation
    * If we want to add others in the future it can be reflected by specific names  

##  TODO's (Pending)

- [ ] Implement/Setup a `SQLA` driver based on the `dbapi` wrapper (`exasol.driver.websocket`)
- [ ] Implement/Setup the newly added test setup with the CI/CD infrastructure
- [ ] Cleanup

**Comment by Nicoretti** [comment]
# Status Update
First draft of a websocket based dialect was added (see #320).
The current results of the SQLA compliance test suite are the following:

SQLA - Compliance Test Suite
---
1 :heavy_check_mark: Passed , 287 :heavy_multiplication_x: Failed , 305 :yellow_circle: Ignored

**Comment by Nicoretti** [comment]
# Status Update

SQLA - Compliance Test Suite
---
142 :heavy_check_mark: Passed , 50 :heavy_multiplication_x: Failed , 365 :yellow_circle: Ignored


for further details see #320

**Comment by Nicoretti** [comment]
# Status Update

SQLA - Compliance Test Suite
---
147 :heavy_check_mark: Passed , 45 :heavy_multiplication_x: Failed , 365 :yellow_circle: Ignored


for further details see #320

**Comment by Nicoretti** [comment]
# Status Update

SQLA - Compliance Test Suite
---
149 :heavy_check_mark: Passed , 43 :heavy_multiplication_x: Failed , 365 :yellow_circle: Ignored


for further details see #320

**Comment by Nicoretti** [comment]
# Status Update

SQLA - Compliance Test Suite
---
152 :heavy_check_mark: Passed , 40 :heavy_multiplication_x: Failed , 365 :yellow_circle: Ignored


for further details see #320 

:spiral_notepad: Note
Looks like most of the remaining failing tests are due to incorrect/missing DBAPI type conversions.

**Comment by Nicoretti** [comment]
# Status Update

SQLA - Compliance Test Suite
---
162 :heavy_check_mark: Passed , 30 :heavy_multiplication_x: Failed , 365 :yellow_circle: Ignored


for further details see #320

**Comment by Nicoretti** [comment]
# Status Update

SQLA - Compliance Test Suite
---
172 :heavy_check_mark: Passed , 20 :heavy_multiplication_x: Failed , 365 :yellow_circle: Ignored

for further details see #320

**Comment by Nicoretti** [comment]
# Status Update

SQLA - Compliance Test Suite
---
176 :heavy_check_mark: Passed , 15 :heavy_multiplication_x: Failed , 366 :yellow_circle: Ignored

for further details see #320

**Comment by Nicoretti** [comment]
# Status Update

SQLA - Compliance Test Suite
---
178 :heavy_check_mark: Passed , 13 :heavy_multiplication_x: Failed , 366 :yellow_circle: Ignored

for further details see #320

**Comment by Nicoretti** [comment]
# Status Update
As of today, the websocket dialect, did not pass 100% of the expected SQLA compliance test suite. Still we expect the basic features to work. Therefore, the decision was made to release a beta version. This will give us a faster feedback cycle and allow users to test and play around with the new functionality. Once the websocket driver is stabilized it will be announced and
marked accordingly.

## Test Status
SQLA - Compliance Test Suite
---
178 :heavy_check_mark: Passed , 13 :heavy_multiplication_x: Failed , 366 :yellow_circle: Ignored

Exasol - Test Suite
---
181 :heavy_check_mark: Passed , 1 :heavy_multiplication_x: Failed , 29 :yellow_circle: Ignored

for further details see #320 

 
### Remaining Todo's
- [x] Create follow up issues
     - #341 
     - #342 
- [x] Fix the remaining failing test of the Exasol test suite (TLS)
- [x] Add notes regarding the Beta status of the Dialect to the README
- [x] Add basic usage information to the README 
- [ ] Add xfail exceptions for the remaining failing tests in the SQLA test suite

Once the related PR #320 is merged s new release, containing the beta should be created.

**Comment by Nicoretti** [comment]
# Status Update

## Test Status

### Exasol - Test Suite  :heavy_check_mark: 

### SQLA - Compliance Test Suite
178 :heavy_check_mark: Passed , 13 :heavy_multiplication_x: Failed , 366 :yellow_circle: Ignored

---
for further details see #320 

 
### Remaining Todo's
- [x] Add xfail exceptions for the remaining failing tests in the SQLA test suite
     - Update information in follow up tickets
         -  #341 
         -  #342

Once the related PR #320 is merged s new release, containing the beta should be created.
