### ISSUE TITLE
Update/Integrate latest bugfix release of sqlalchemy dependency

### ISSUE THREAD

**Issue by Nicoretti** [exasol/sqlalchemy-exasol#125]
## Summary
Update sqlalchemy from `1.3.9` to `1.3.24`

## Tasks
- [x] update dependency
- [x] address issues of integration tests which have been added with the new version
  - [x] `LongNameBlowoutTest:::test_long_convention_name[fk-_exclusions0]` (**failing**)
  - [x] `LongNameBlowoutTest:::test_long_convention_name[pk-_exclusions1]` (**failing**)
  - [x] `LongNameBlowoutTest:::test_long_convention_name[ix-_exclusions2]`  (**not implemented**)
