### ISSUE TITLE
Migrate project to a pyproject.toml based package setup

### ISSUE THREAD

**Issue by Nicoretti** [exasol/sqlalchemy-exasol#128]
## Why
Currently the project packaging, configuration and dependencies are managed using a mix of input sources.
E.g. dependencies are defined in `setup.py` and in various requirements files (`requirements.txt` etc.).
Modern python projects use a common "project-file" which takes care about lots of things which have been
done by multiple inputs like (`MANIFEST.in, setup.cfg, setup.py, requirements.txt, ...`).

Switching to `pyproject.toml` therefore will simplify maintenance and release efforts of the package.

For further details see also: 
* [Poetry](https://python-poetry.org/)
* [PEP 517](https://peps.python.org/pep-0517/)
* [PEP 518](https://peps.python.org/pep-0518/)
* [PEP 621](https://peps.python.org/pep-0621/)
* [PEP 660](https://peps.python.org/pep-0660/)

## Tasks
- [x] Add `pyproject.toml`
  - [x] Add requirements 
  - [x] Add dev requirements
  - [x] Add extra requirements
  - [x] Add test requirements
- [x] Add poetry.lock
- [x] Move configuration(s) into `pyproject.toml`
  - [x] setup.cfg
  - [x] MANIFEST.in
- [x] Remove .ptup.yaml
- [x] Add support for Dependabot
- [x] Change GH-Action to build and deploy using poetry
