### ISSUE TITLE
Remove support for Python < 3.8

### ISSUE THREAD

**Issue by MarleneKress79789** [exasol/sqlalchemy-exasol#135]
This project supports python version >= 3.7. We want to remove older python versions. 
* Remove support for python version < 3.8

**Comment by Nicoretti** [comment]
## TODO's to keep in mind for the migration

- [x] Change version provider of package version to installation metadata ([see also](https://github.com/exasol/sqlalchemy-exasol/pull/145#discussion_r885733975))
    - Remove version file
    - Remove commit hook
    - Remove verifier step
- [x] Add a note to the release notes that we dropped `3.7` knowingly previous to EOL, if that should be a issue for somebody they should drop us a mail or file an issue.
- [x] Continue versioning with `3.X.Y` so the `2.X.Y` series can be used for backports if needed.
