### ISSUE TITLE
Extract all functionality which isnt' a task itself from the noxfile

### ISSUE THREAD

**Issue by Nicoretti** [exasol/sqlalchemy-exasol#147]
## Description
In order to keep the noxfile clean and simplify code sharing in the future, the noxfile only should contain
the actual tasks itself. This can be achieved by moving python code needed by the tasks into modules and script files which export the appropriate functionality.

## Task's
- [ ] extract all obdc related functionality into `scripts/odbc.py`
- [ ] extract session finder into `scripts/nox_utils.py`
- [ ] extract settings
   - [ ] create a settings file
   - [ ] provide a "reader" for the settings file

**Comment by Nicoretti** [comment]
Having common nox code/functionality, will be covered by the python-toolbox in the future.
