### ISSUE TITLE
Add support for automated code formatting

### ISSUE THREAD

**Issue by Nicoretti** [exasol/sqlalchemy-exasol#162]
## Summary
Add support for automated code formatting using the [black code formatter](https://github.com/psf/black).

## Tasks
- [x] Add black to dev dependencies
- [x] Add configuration section to `pyproject.toml`
   ```
   [tool.black]
   line-length = 88
   verbose = false
   include = "\\.pyi?$"
   ```
- [x] Run initial code formatting on entire code base, [see also](https://black.readthedocs.io/en/stable/guides/introducing_black_to_your_project.html).
- [x] Add/Extend Check target in `noxifle.py`, which automatically will check code formatting 
- [x] Add/Extend Fix target in `noxifle.py`, which automatically will fix code formatting 
- [x] Add CI/CD check(s) if code is properly formatted
- [x] Add `code style` badge to project, ![see also](https://img.shields.io/badge/code%20style-black-000000.svg).
