### ISSUE TITLE
Add support for type checks and type annotations

### ISSUE THREAD

**Issue by Nicoretti** [exasol/sqlalchemy-exasol#164]
## Summary
Add support for type checking code using [mypy](https://github.com/python/mypy).

## Tasks
- [x] Add mypy to dev dependencies
- [x] Add configuration section to `pyproject.toml`
   ```
   [tool.mypy]
   files = [
       'noxfile.py',
       'scripts/**/*.py',
   ]
   ```
- [x] Add mypy target in `noxifle.py`
  ```python
  @nox.session(python=False)
  def mypy(session: Session) -> None:
      session.run(
          "poetry",
          "run",
          "mypy",
          "--strict",
          "--show-error-codes",
          "--pretty",
          "--show-column-numbers",
          "--show-error-context",
          "--scripts-are-modules",
      )
  ```
- [x] Fix initial types issues for currently configured/tracked files.
- [ ] ~~Create a follow up issue to add type hints to "entire code base".~~
- [x] Add/Extend check of verify target in `noxifle.py`, which automatically will check for type hints.
- [x] Add CI/CD check(s) if code provides all necessary type hints etc.
- [x] Add `mypy` badge to project, ![see also](http://www.mypy-lang.org/static/mypy_badge.svg).
