### ISSUE TITLE
Add static code analyzer

### ISSUE THREAD

**Issue by Nicoretti** [exasol/sqlalchemy-exasol#165]
## Summary
Add support for static code analysis using [pylint](https://github.com/PyCQA/pylint).

## Tasks
- [x] Add pylint to dev dependencies
- [x] Add configuration section to `pyproject.toml`
   ```
   [tool.pylint.master]
   fail-under = 8 # base line needs to be set by project

   [tool.pylint.format]
   max-line-length = 88
   max-module-lines = 800

   [tool.pylint.message_control]
   disable = "C0330, C0326"
   ```
- [x] Add pylint target in `noxifle.py` e.g.:
  ```python
   @nox.session(python=False)
   def pylint(session: Session) -> None:
       session.run("poetry", "run", "python", "-m", "pylint", f'{BASEPATH / "prysk"}')
       session.run("poetry", "run", "python", "-m", "pylint", f'{BASEPATH / "scripts"}')
  ```
- [x] Run and add initial score as baseline for `fail-under` setting
- [ ] ~~Create a follow up issue to add type hints to "entire code base".~~
  - [ ] ~~Add issue template for fixing found issues~~
- [x] Add/Extend check of verify target in `noxifle.py`, which automatically will checks against baseline.
- [x] Add CI/CD check(s) against baseline.
- [x] Add `pylint` badge to project reflecting baseline value e.g. ![see also](https://img.shields.io/badge/pylint-8.0-green).
  * 0 - 3 red
  * \>=3, <5 orange
  * \>=5, <7 yellow
  * \>=7, <9 green
  * \>=9       brigth green
