### ISSUE TITLE
Add scriv to simplify creating/updateing the changelog

### ISSUE THREAD

**Issue by Nicoretti** [exasol/sqlalchemy-exasol#166]
## Summary
Add [scriv](https://github.com/nedbat/scriv) to simplify creating and updating the  change log.
(Get rid of the unversioned "not released" log entries etc.)

## Tasks
- [ ] Add scriv to dev dependencies
- [ ] Add configuration section to `pyproject.toml`
- [ ] Update release target accordingly, e.g. add check if change log was written and committed. 
- [ ] Add templates if needed
