### ISSUE TITLE
Rework usage of pyupgrade

### ISSUE THREAD

**Issue by Nicoretti** [exasol/sqlalchemy-exasol#167]
## Summary
Rework the usage of the [pyupgrade](https://github.com/asottile/pyupgrade) tool, to be part of the code style (black, isort, ...) checks and verification.

## Tasks
- [x] Remove pyupgrade from precomit hooks
- [x] Add pyupgrade target to `noxfile.py` 
- [x] Add pyupgrade target to be part of the following targets verify/check/fix
