### ISSUE TITLE
Add coverage information/support to project

### ISSUE THREAD

**Issue by Nicoretti** [exasol/sqlalchemy-exasol#168]
## Summary
Add support for checking and visualizing the code cover of the project using:
* [Coverage.py](https://coverage.readthedocs.io/en/6.4.2/)

## Tasks
- [ ] Add `coverage.py` to dev dependencies
- [ ] Add configuration section to `pyproject.toml`
- [ ] Run initial code coverage aggregation
   - [ ] Integration & Unit Tests are considered 
   - [ ] consider adding/failing on baseline or minimum coverage (sonar rules)
- [ ] Add/Extend check/target in `noxifle.py`, which will run/accumulate the code coverage.
- [ ] Add CI/CD check(s)
- [ ] Add follow up ticket
   - [ ] Add template for follow up tickets
   - [ ] Add follow up ticket(s) to improve coverage if necessary

**Comment by Nicoretti** [comment]
By adding the[ `python-toolbox`](https://github.com/exasol/python-toolbox) KPI/statistics support this issue would be addressed implicitly.
