### ISSUE TITLE
Migrate documenation to sphinx

### ISSUE THREAD

**Issue by Nicoretti** [exasol/sqlalchemy-exasol#170]
## Summary
Migrate entire documentation to [sphinx](https://www.sphinx-doc.org/en/master/).

## Tasks
- [x] Add `sphinx` to dev dependencies
- [x] Add `furo` theme to dev dependencies
- [x] Add configuration 
- [x] Add nox target(s)
  - [x] build doc(s)
  - [x] open doc(s)
- [x] Add documentation to diliverable (wheel, tgz ...)
- [x] Add Github action
   - [x] Gh-pages branch with latest documentation
 -  [ ] ~~Create follow up ticket to host and publish multi version doc(s)~~
