### ISSUE TITLE
Add support for sonar cloud

### ISSUE THREAD

**Issue by Nicoretti** [exasol/sqlalchemy-exasol#171]
## Summary
Add support for [sonar cloud](https://sonarcloud.io/projects) "check(s)" for this project. 

## Pre Requisite(s)
* #164 
* #165 
* #167 
* #168 

## Tasks
- [ ] Enable sonar cloud for the projects
- [ ] Configure sonar cloud to use existing tools & checks where possible
- [ ] Add sonar cloud code quality badges

**Comment by Nicoretti** [comment]
Should be taken care of by the python toolbox in the future.
