### ISSUE TITLE
🔧 Address linter issues (Improve Pylint Score)

### ISSUE THREAD

**Issue by Nicoretti** [exasol/sqlalchemy-exasol#183]
## Summary
Fix linter issue to reach a new baseline score of at least `7.0`.

### How to run the linter

```shell
nox -s lint
```

## Tasks
- [ ] Fix linter messages in regard to the following priorities
   - Fatal
   - Error
   - Warning
   - Convention
   - Refactor
   - Information
- [ ] Update new baseline (`>= 7.0`) in the configuration `pyproject.toml` and in the `pylint badge`.
  - 0 - 3 red
  - \>=3, <5 orange
  - \>=5, <7 yellow
  - \>=7, <9 green
  - \>=9       brigth green
- [ ] Create a follow up ticket to improve the pylint score to >= `8.0`

**Comment by Nicoretti** [comment]
This issue is partially deprecated, KPI reporting will made available using the `python-toolbox` in the future.
The update of the current status is done as part of #105, #320.
