### ISSUE TITLE
✨ Add support for sphinx github pages generator

### ISSUE THREAD

**Issue by Nicoretti** [exasol/sqlalchemy-exasol#184]
## Summary
Add support for hosting multiple version(s) of the documentation on gh pages.

For more details [see also](https://github.com/exasol/sphinx-github-pages-generator)

## Tasks
- [ ] Add `sphinx-github-pages-generator` as dev dependency 
- [ ] Add link/reference to docs page (gh-pages) to README
- [ ] Add necessary nox task(s)
- [ ] Update gh-pages action accordingly

**Comment by Nicoretti** [comment]
Obsolete, will be taken care of by the exasol-toolbox in the future.
