### ISSUE TITLE
✨ Add typing support to sqlalchemy_exasol package

### ISSUE THREAD

**Issue by Nicoretti** [exasol/sqlalchemy-exasol#187]
## Summary
Add type hints to `sqlalchemy-exasol` package.

### Run type checker
```
nox -s type-check
```

## Tasks
- [ ] Add sqlalchemy module to mypy configuration section in `pyproject.toml`
   ```
   [tool.mypy]
   files = [
       'noxfile.py',
       'scripts/**/*.py',
       'sqlalchemy_exasol/**/*.py'
   ]
   ```
- [ ] Fix missing type hints
- [ ] If there still modules missing type hints, create a follow up issue.
- [ ] Add `mypy` badge to project, ![see also](http://www.mypy-lang.org/static/mypy_badge.svg).

**Comment by Nicoretti** [comment]
Closing this issue, this will come up when we integrate the [`python-toolbox`](https://github.com/exasol/python-toolbox) anyway.
