### ISSUE TITLE
 ✨ Add caching support for Exasol Dialects in respect to SQLA 1.4

### ISSUE THREAD

**Issue by Nicoretti** [exasol/sqlalchemy-exasol#190]
## Summary
Implement caching support for exasol dialects in order to achieve optimal performance with `SQLAlachemy >=  1.4`.

### Additional information
- [Engine thridparty caching](https://docs.sqlalchemy.org/en/14/core/connections.html#engine-thirdparty-caching)
- [Why is my application slow after upgrading to 1.4 and/or 2.x](https://docs.sqlalchemy.org/en/14/faq/performance.html#why-is-my-application-slow-after-upgrading-to-1-4-and-or-2-x)
## Tasks
- [ ] Implement caching support for pyodbc based dialect
- [ ] Implement caching support for turbodbc based dialect
- [ ] Add note to release notes that potential performance penalty have been addressed/fixed

## Related Issues
- [x] exasol/sqlalchemy-exasol#106

**Comment by ArBridgeman** [comment]
With https://github.com/exasol/sqlalchemy-exasol/issues/413 and the release version 6.0.0, turbodbc and pyodbc are no longer supported.
