### ISSUE TITLE
🔧 Update Integration Test Docker Environment to 1.5.0

### ISSUE THREAD

**Issue by Nicoretti** [exasol/sqlalchemy-exasol#219]
# Summary
Use the ITDE (Integration Test Docker Environment) version to `latest` version for the test setup.

# Details
Catchup on the ITDE is required.

## Background & Context
New features and DB version are supported by the latest ITDE version.

## References
* https://github.com/exasol/sqlalchemy-exasol/pull/191#discussion_r987105238

# Task(s)
- [ ] update GitHub workflows to use the version tag `latest` of ITDE
- [ ] update change log
- [ ] bump version number
