### ISSUE TITLE
📦 Update SqlAlchemy package to version >=1.4 < 2.0.0

### ISSUE THREAD

**Issue by Nicoretti** [exasol/sqlalchemy-exasol#276]
# Summary
Update SqlAlchemy package to version >1.4.44 < 2.0.0 and address potential issue.

# Details
Updating to the latest SQLA version `1.4.X` where `X` is > `44` does not work out of the box.
Some of the `compliance tests` provided by SQLA are failing. Therefore an update of `sqlalchemy` 
within the context of `sqlalchemy-exasol` also needs address those issues.

## Background & Context
1. Do an overall dependency update
    ```
    poetry update 
    ```
    or just for sqla
    ```
    poetry update SqlAlchemy
    ```

2. Check the test results
    
    ```
    poetry run nox -s integration-tests
    ```

3. Address Issue(s)

    * Fix
    * Disable temporarily (xfail) and create a dedicated issue for investigation/fixing.
    * Suppress/Disable with rational if applicable (e.g. not supported DB feature)
    
## References
* Dependabot PR https://github.com/exasol/sqlalchemy-exasol/pull/274

# Task(s)

- [ ] Update SQLAlchemy to the latest version > 1.4.44 < 2.0.0
- [ ] Address failing sqla compliance tests
- [ ] Bump version number
- [ ] Update change log
